require_relative 'blas_L1/amax.rb'
require_relative 'blas_L1/asum.rb'
require_relative 'blas_L1/axpy.rb'
require_relative 'blas_L1/copy.rb'
require_relative 'blas_L1/dot.rb'
require_relative 'blas_L1/nrm.rb'
require_relative 'blas_L1/scal.rb'
require_relative 'blas_L1/swap.rb'
require_relative 'blas_L1/rotg.rb'
require_relative 'blas_L1/rot.rb'

require_relative 'lapack/gesv.rb'
require_relative 'lapack/getrf.rb'
require_relative 'lapack/getrs.rb'
