
all: 
	Make -C classes
	Make -C rb_blas_extras
	Make -C rb_blas_l1_functions
	Make -C rb_blas_l2_functions
	Make -C rb_blas_l3_functions

clean:
	Make -C classes clean
	Make -C rb_blas_extras clean
	Make -C rb_blas_l1_functions clean
	Make -C rb_blas_l2_functions clean
	Make -C rb_blas_l3_functions clean
